/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyfinal;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static proyfinal.Tabla_Hash.i;



public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    
    String[][] content = Tabla_Hash.orden; // Aquí igualan a su matriz con el contenido
    String columns[] = { "Token", "Tipo", "Instancia"};
    JTable table = new JTable(content, columns);
    public PrincipalFrame() {
        initComponents();
        
    }
    
    public static String repeat(int n) {
        String spaces = "";
        for(int i=0; i<n; i++) {
            spaces += " ";
        }
        return spaces;
    }
    
    public static class Token {
        public final String t;
        public final Palabra p;

        public Token(String t, Palabra p) {
            this.t = t;     // token
            this.p = p;     // item de palabra
        }
        
    }
    
    public static void SintaxException(int linea, int index, String palabra) {
        String message = "<html><pre>Error en la linea " + linea + "," + index + ":";
        message += "<br>" + palabra + "<br>" + repeat(index) + "^";
        message += "<br>Error sintáctico: sintáxis inválida</html>";
        JLabel label = new JLabel(message);
        label.setFont(new Font("Consolas", Font.BOLD, 14));
        JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);
    }

    public static void LexicException(int linea, int index, String palabra, String detalle) {
        String message = "<html><pre>Error en la linea " + linea + "," + index + ":";
        message += "<br>" + palabra + "<br>" + repeat(index) + "^";
        message += "<br>Error léxico:"+ detalle+ "</html>";
        JLabel label = new JLabel(message);
        label.setFont(new Font("Consolas", Font.BOLD, 14));
        JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);
    }

    


    public static void mostrarTablaSimbolos()
    {
        String[][] content = Tabla_Hash.orden; // Aquí igualan a su matriz con el contenido
        String columns[] = { "Token", "Tipo", "Instancia"};
        JTable table = new JTable(content, columns);
        Font font = new Font("Verdana", Font.PLAIN, 12);
        table.setFont(font);
        table.setRowHeight(30);
        JFrame frame = new JFrame();
        frame.setSize(600, 400);
        frame.add(new JScrollPane(table));
        frame.setVisible(true); 
    }
    
public void limpiarTabla(JTable tabla){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelBienvenido = new javax.swing.JLabel();
        LabelIngresar = new javax.swing.JLabel();
        btnvalidar = new javax.swing.JButton();
        btnSel = new javax.swing.JButton();
        LabelIngresar1 = new javax.swing.JLabel();
        txtInfo = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelBienvenido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelBienvenido.setText("Bienvenido");

        LabelIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelIngresar.setText("Ingrese los datos");

        btnvalidar.setText("Validar");
        btnvalidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalidarActionPerformed(evt);
            }
        });

        btnSel.setText("Examinar archivo txt");
        btnSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelActionPerformed(evt);
            }
        });

        LabelIngresar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelIngresar1.setText("ó");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtInfo.setViewportView(txtArea);

        jButton1.setText("Mostrar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(LabelIngresar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSel))
                            .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(LabelBienvenido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(LabelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnvalidar)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelIngresar)
                .addGap(19, 19, 19)
                .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LabelIngresar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSel)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(btnvalidar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnvalidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidarActionPerformed
        Tabla_Hash limpiar = new Tabla_Hash(1);//<----------------Limpiar matriz orden[][]
        limpiar.ClearOrden();
        limpiarTabla(table);
        Boolean valid=true;
        List<Palabra> palabras = new ArrayList<>();
        List<Token> tokens = new ArrayList<Token>();
        
        //String path ="6.txt";
        Lexer analizadorLexico = new Lexer();
        ReadFile fileReader = new ReadFile();
        
        palabras = fileReader.ReadTxt(txtArea.getText());
        //System.out.println(palabras);
        for (Palabra item : palabras) {
            String token = analizadorLexico.tokenize(item.palabra);
            String detalle="";
            if(token != null){
                tokens.add(new Token(token, item));
            } else {
                //// ERROR LÉXICO
                if(item.palabra.contains("@"))
                    detalle = "El email debe seguir la estructura \"ejemplo@dominio.com\" y las extensiones válidas son:<br>.com<br>.es<br>.net<br>.org<br>.edu";
                else if(item.palabra.matches("[0-9]+"))
                    detalle = "El número de teléfono debe seguir la estructura \"6###-####\"";
                LexicException(item.linea, item.index,
                                fileReader.getContent(item.linea - 1), detalle);
                valid = false;
                //return;
                //System.exit(1); // para que no imprima lo que sigue
            }
        }
        
        System.out.println("Tokens:");
        if(valid){
            System.out.println("Tokens:");
            String previous = "";
            for (Token token : tokens) {
                System.out.print(token.t + ": " + token.p.palabra);
                System.out.println("");
                if ((previous.equals("") && !token.t.startsWith("CONT"))
                        || (previous.startsWith("CONT") && !token.t.startsWith("CONT"))
                        || previous.startsWith(token.t.substring(4))) {
                } else {
                    //// ERROR SINTÁCTICO
                    
                    SintaxException(token.p.linea, token.p.index,
                                    fileReader.getContent(token.p.linea - 1));
                    //System.exit(1); // para que no siga
                    //return;
                    valid = false;
                }
                previous = token.t;
            }
        }
        
        if(valid) { JOptionPane.showMessageDialog(null, "Validado"); }
    }//GEN-LAST:event_btnvalidarActionPerformed

    
    private void btnSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo = fc.getSelectedFile();
        try{
            FileReader fr = new FileReader (archivo);
            BufferedReader br = new BufferedReader (fr);
            String texto ="";
            String linea ="";
            while(((linea = br.readLine())!=null)){
                texto+=linea + "\n";
            }
            txtArea.setText(texto);
            JOptionPane.showMessageDialog(null, "Archivo leido correctamente");
            
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnSelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarTablaSimbolos();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBienvenido;
    private javax.swing.JLabel LabelIngresar;
    private javax.swing.JLabel LabelIngresar1;
    private javax.swing.JButton btnSel;
    private javax.swing.JButton btnvalidar;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JScrollPane txtInfo;
    // End of variables declaration//GEN-END:variables
}
