/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyfinal;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JLabel;


public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
        
    }
    
    public static String repeat(int n) {
        String spaces = "";
        for(int i=0; i<n; i++) {
            spaces += " ";
        }
        return spaces;
    }
    
    public static class Token {
        public final String t;
        public final Palabra p;

        public Token(String t, Palabra p) {
            this.t = t;     // token
            this.p = p;     // item de palabra
        }
        
    }
    
    public static void SintaxException(int linea, int index, String palabra) {
        String message = "<html><pre>Error en la linea " + linea + "," + index + ":";
        message += "<br>" + palabra + "<br>" + repeat(index) + "^";
        message += "<br>Error sintáctico: sintáxis inválida</html>";
        JLabel label = new JLabel(message);
        label.setFont(new Font("Consolas", Font.BOLD, 14));
        JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);
    }

    public static void LexicException(int linea, int index, String palabra) {
        String message = "<html><pre>Error en la linea " + linea + "," + index + ":";
        message += "<br>" + palabra + "<br>" + repeat(index) + "^";
        message += "<br>Error léxico: palabra inválida</html>";
        JLabel label = new JLabel(message);
        label.setFont(new Font("Consolas", Font.BOLD, 14));
        JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);
    }

    public static void mostrarTablaSimbolos(){
        String[][] content; // Aquí igualan a su matriz con el contenido
        String columns[] = { "Hash", "Contenido", "Token", "Indice"};
        JTable table = new JTable(content, columns);
        Font font = new Font("Verdana", Font.PLAIN, 12);
        table.setFont(font);
        table.setRowHeight(30);
        JFrame frame = new JFrame();
        frame.setSize(600, 400);
        frame.add(new JScrollPane(table));
        frame.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelBienvenido = new javax.swing.JLabel();
        LabelIngresar = new javax.swing.JLabel();
        btnvalidar = new javax.swing.JButton();
        btnSel = new javax.swing.JButton();
        LabelIngresar1 = new javax.swing.JLabel();
        txtInfo = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validación");

        LabelBienvenido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelBienvenido.setText("Bienvenido");

        LabelIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelIngresar.setText("Ingrese los datos");

        btnvalidar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnvalidar.setText("Validar");
        btnvalidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalidarActionPerformed(evt);
            }
        });

        btnSel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSel.setText("Examinar archivo txt");
        btnSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelActionPerformed(evt);
            }
        });

        LabelIngresar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelIngresar1.setText("ó");

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtArea.setRows(5);
        txtInfo.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(LabelBienvenido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelIngresar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnSel)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(LabelIngresar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnvalidar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelBienvenido)
                .addGap(7, 7, 7)
                .addComponent(LabelIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelIngresar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvalidar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnvalidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidarActionPerformed
        // TODO add your handling code here:
        List<Palabra> palabras = new ArrayList<>();
        List<Token> tokens = new ArrayList<Token>();
        
        //String path ="./4.txt";
        Lexer analizadorLexico = new Lexer();
        ReadFile fileReader = new ReadFile();
        
        boolean valid = true;
        
        palabras = fileReader.ReadTxt(txtArea.getText());
        //System.out.println(palabras);
        for (Palabra item : palabras) {
            String token = analizadorLexico.tokenize(item.palabra);
            if(token != null){
                tokens.add(new Token(token, item));
            } else {
                //// ERROR LÉXICO
                LexicException(item.linea, item.index,
                                fileReader.getContent(item.linea - 1));
                valid = false;
                //return;
                //System.exit(1); // para que no imprima lo que sigue
            }
        }
        
        System.out.println("Tokens:");
        String previous = "";
        for (Token token : tokens) {
            System.out.print(token.t + ": " + token.p.palabra);
            System.out.println("");
            if ((previous.equals("") && !token.t.startsWith("CONT"))
                    || (previous.startsWith("CONT") && !token.t.startsWith("CONT"))
                    || previous.startsWith(token.t.substring(4))) {
            } else {
                //// ERROR SINTÁCTICO
                SintaxException(token.p.linea, token.p.index,
                                fileReader.getContent(token.p.linea - 1));
                //System.exit(1); // para que no siga
                //return;
                valid = false;
            }
            previous = token.t;
        }
        
        if(valid) { JOptionPane.showMessageDialog(null, "Validado"); }
    }//GEN-LAST:event_btnvalidarActionPerformed

    
    private void btnSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo = fc.getSelectedFile();
        try{
            FileReader fr = new FileReader (archivo);
            BufferedReader br = new BufferedReader (fr);
            String texto ="";
            String linea ="";
            while(((linea = br.readLine())!=null)){
                texto+=linea + "\n";
            }
            txtArea.setText(texto);
            JOptionPane.showMessageDialog(null, "Archivo leido correctamente");
            
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnSelActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBienvenido;
    private javax.swing.JLabel LabelIngresar;
    private javax.swing.JLabel LabelIngresar1;
    private javax.swing.JButton btnSel;
    private javax.swing.JButton btnvalidar;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JScrollPane txtInfo;
    // End of variables declaration//GEN-END:variables
}
